In [19]:
import pandas as pd
import numpy as np

In [20]:
# Load the data
hr_df = pd.read_csv( 'hr_df.csv' )

In [23]:
from sklearn.model_selection import train_test_split


train_X, test_X, train_y, test_y = train_test_split( hr_df[feature_columns],
                                                  hr_df['left'],
                                                  test_size = 0.3,
                                                  random_state = 42 )

## Logistic Reg Model using sklearn

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
logreg = LogisticRegression() #Initialize
logreg.fit( train_X, train_y ) # Fit the model on the train data

C:\Users\Lenovo\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
logreg.predict_proba(train_X)

array([[0.35269749, 0.64730251],
       [0.97423454, 0.02576546],
       [0.46976005, 0.53023995],
       ...,
       [0.8957553 , 0.1042447 ],
       [0.74857504, 0.25142496],
       [0.83504887, 0.16495113]])

In [27]:
logreg.predict_proba(test_X)

array([[0.97047392, 0.02952608],
       [0.91847105, 0.08152895],
       [0.77042819, 0.22957181],
       ...,
       [0.86951973, 0.13048027],
       [0.96789555, 0.03210445],
       [0.98222121, 0.01777879]])

## Decision Tree Model using sklearn

In [28]:
from sklearn import metrics

from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.model_selection import GridSearchCV

### Simple DT Model without hyper param tuning

In [30]:
clf_tree = DecisionTreeClassifier( max_depth = 4 ) #initalize 
clf_tree=clf_tree.fit( train_X, train_y ) # Fir the model on the train dataset

In [31]:
clf_tree.predict_proba(train_X)

array([[0.        , 1.        ],
       [0.98673783, 0.01326217],
       [0.02836231, 0.97163769],
       ...,
       [0.98673783, 0.01326217],
       [0.13409415, 0.86590585],
       [0.98673783, 0.01326217]])

### DT Model with hyper param tuning

In [32]:
param_grid = {'max_depth': np.arange(3, 12),
             'max_features': np.arange(3,10)}

In [33]:
tree = GridSearchCV(DecisionTreeClassifier(), param_grid, cv = 5, scoring='roc_auc')
tree.fit( train_X, train_y )

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': array([ 3,  4,  5,  6,  7,  8,  9, 10, 11]),
                         'max_features': array([3, 4,

In [34]:
tree.best_score_

0.9780870063300234

In [35]:
tree.best_params_

{'max_depth': 10, 'max_features': 8}

In [36]:
tree.best_estimator_

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
                       max_features=8, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [37]:
clf_tree.feature_importances_

array([0.        , 0.05987108, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00065277, 0.15652208, 0.09343631, 0.        , 0.        ,
       0.        , 0.55461756, 0.1349002 ])

# Ensemble Methods

In [38]:
import sklearn.ensemble as en

In [39]:
dir(en)

['AdaBoostClassifier',
 'AdaBoostRegressor',
 'BaggingClassifier',
 'BaggingRegressor',
 'BaseEnsemble',
 'ExtraTreesClassifier',
 'ExtraTreesRegressor',
 'GradientBoostingClassifier',
 'GradientBoostingRegressor',
 'IsolationForest',
 'RandomForestClassifier',
 'RandomForestRegressor',
 'RandomTreesEmbedding',
 'VotingClassifier',
 'VotingRegressor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_gb_losses',
 '_gradient_boosting',
 'bagging',
 'base',
 'forest',
 'gradient_boosting',
 'iforest',
 'partial_dependence',
 'voting',
 'weight_boosting']

#### Bagging without tuning

In [40]:
from sklearn.ensemble import BaggingClassifier

In [41]:
BaggingClassifier?

In [42]:
bagclm = BaggingClassifier(oob_score=True, n_estimators=100, verbose=True, n_jobs=-1)

In [43]:
bagclm.fit(train_X, train_y)

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   2 out of   4 | elapsed:    6.8s remaining:    6.8s
[Parallel(n_jobs=4)]: Done   4 out of   4 | elapsed:    7.2s finished


BaggingClassifier(base_estimator=None, bootstrap=True, bootstrap_features=False,
                  max_features=1.0, max_samples=1.0, n_estimators=100,
                  n_jobs=-1, oob_score=True, random_state=None, verbose=True,
                  warm_start=False)

In [44]:
bagclm.predict(train_X)

[Parallel(n_jobs=4)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=4)]: Done   2 out of   4 | elapsed:    0.2s remaining:    0.2s
[Parallel(n_jobs=4)]: Done   4 out of   4 | elapsed:    0.2s finished


array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

In [45]:
bagclm.oob_score_

0.9889513286979712

### Random Forest 

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
radm_clf = RandomForestClassifier(oob_score=True,n_estimators=100 , max_features=6, n_jobs=-1)
radm_clf.fit( train_X, train_y )

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features=6, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=-1, oob_score=True, random_state=None, verbose=0,
                       warm_start=False)

In [49]:
radm_clf.feature_importances_

array([0.00613538, 0.14417217, 0.00161816, 0.00150048, 0.00144312,
       0.00116272, 0.00102306, 0.00070261, 0.00287528, 0.00198705,
       0.00372263, 0.11769441, 0.17638534, 0.0012152 , 0.0053864 ,
       0.00322651, 0.34857598, 0.18117351])

#### Random Forest w/t tuning

In [50]:
pargrid_rf = {'n_estimators': [50, 60, 70, 80, 90, 100],
                  'max_features': [5,6,7,8,9,10]}

In [51]:
gscv_rf = GridSearchCV(estimator=RandomForestClassifier(), 
                        param_grid=pargrid_rf, 
                        cv=5,
                        verbose=True, n_jobs=-1)

In [52]:
gscv_results = gscv_rf.fit(train_X, train_y)

Fitting 5 folds for each of 36 candidates, totalling 180 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   23.2s
[Parallel(n_jobs=-1)]: Done 180 out of 180 | elapsed:  1.4min finished


In [54]:
gscv_results.best_params_

{'max_features': 8, 'n_estimators': 80}

In [55]:
gscv_results.best_score_

0.9899038003619393

### AdaBoost

In [56]:
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [57]:
# Tuning the AdaBoost

In [58]:
pargrid_ada = {'n_estimators': [100, 200, 400, 600, 800],
               'learning_rate': [10 ** x for x in range(-3, 3)]}

In [60]:
gscv_ada = GridSearchCV(estimator=AdaBoostClassifier(), 
                        param_grid=pargrid_ada, 
                        cv=5,
                        verbose=True, n_jobs=-1)

In [61]:
gscv_ada.fit(train_X, train_y)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 150 out of 150 | elapsed:  4.0min finished


GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=AdaBoostClassifier(algorithm='SAMME.R',
                                          base_estimator=None,
                                          learning_rate=1.0, n_estimators=50,
                                          random_state=None),
             iid='warn', n_jobs=-1,
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 1, 10, 100],
                         'n_estimators': [100, 200, 400, 600, 800]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=True)

In [62]:
gscv_ada.best_params_

{'learning_rate': 0.1, 'n_estimators': 800}

## KNN

In [63]:
from sklearn.neighbors import KNeighborsClassifier

In [64]:
knn_clf = KNeighborsClassifier(n_neighbors=5)
knn_clf.fit(train_X, train_y )

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [68]:
print(metrics.classification_report(test_y, knn_clf.predict(test_X)))

              precision    recall  f1-score   support

           0       0.97      0.94      0.96      3428
           1       0.83      0.91      0.87      1072

    accuracy                           0.93      4500
   macro avg       0.90      0.93      0.91      4500
weighted avg       0.94      0.93      0.94      4500



### Performing KNN with hyper-parametr tuning

In [69]:
tuned_parameters = [{'n_neighbors': [3,5, 7, 9,11]}]

In [70]:
knn_clf = GridSearchCV(KNeighborsClassifier(),
                   tuned_parameters,
                   cv=5,
                   scoring='accuracy')

In [71]:
knn_clf.fit(train_X, train_y )

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='warn', n_jobs=None,
             param_grid=[{'n_neighbors': [3, 5, 7, 9, 11]}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [72]:
knn_clf.best_score_

0.9385655776740642

In [73]:
knn_clf.best_params_

{'n_neighbors': 5}

In [74]:
?KNeighborsClassifier